'use client'

import React from 'react'

export interface ReportData {
  title: string
  track: string
  date: string
  drivers: string[]
  sections: ReportSection[]
}

export interface ReportSection {
  title: string
  type: 'text' | 'chart' | 'table' | 'stats'
  content: any
  metadata?: {
    chartImage?: string
    tableData?: any[]
    stats?: Record<string, any>
  }
}

class F1ReportExporter {
  private styles = `
    <style>
      @media print {
        body { font-family: Arial, sans-serif; margin: 20px; line-height: 1.4; }
        .report-header { border-bottom: 2px solid #d32f2f; padding-bottom: 20px; margin-bottom: 30px; }
        .report-title { font-size: 24px; font-weight: bold; color: #333; margin-bottom: 10px; }
        .report-subtitle { font-size: 16px; color: #666; margin-bottom: 15px; }
        .report-meta { font-size: 12px; color: #888; }
        .section-title { font-size: 14px; font-weight: bold; color: #333; margin: 20px 0 10px 0; border-bottom: 1px solid #ddd; padding-bottom: 5px; }
        .section-content { font-size: 12px; color: #555; margin-bottom: 15px; }
        .stats-grid { display: grid; grid-template-columns: repeat(2, 1fr); gap: 10px; margin: 15px 0; }
        .stat-item { padding: 8px; background: #f5f5f5; border-radius: 4px; }
        .stat-label { font-weight: bold; font-size: 11px; }
        .stat-value { font-size: 12px; color: #d32f2f; }
        .report-table { width: 100%; border-collapse: collapse; margin: 15px 0; font-size: 11px; }
        .report-table th { background: #f0f0f0; padding: 8px; text-align: left; font-weight: bold; border: 1px solid #ddd; }
        .report-table td { padding: 6px 8px; border: 1px solid #ddd; }
        .report-footer { margin-top: 30px; padding-top: 20px; border-top: 1px solid #ddd; font-size: 10px; color: #888; text-align: center; }
        .page-break { page-break-before: always; }
        .no-print { display: none !important; }
        .chart-placeholder { background: #f9f9f9; border: 1px dashed #ccc; padding: 20px; text-align: center; color: #666; margin: 15px 0; }
        @page { margin: 20mm; }
      }
      @media screen {
        .print-only { display: none !important; }
      }
    </style>
  `

  generatePrintHTML(data: ReportData): string {
    const sectionsHTML = data.sections.map(section => this.generateSectionHTML(section)).join('')
    
    return `
      <!DOCTYPE html>
      <html>
        <head>
          <title>${data.title}</title>
          ${this.styles}
        </head>
        <body>
          <div class="report-header">
            <div class="report-title">${data.title}</div>
            <div class="report-subtitle">Track Analysis Report</div>
            <div class="report-meta">
              <div>Track: ${data.track}</div>
              <div>Date: ${data.date}</div>
              <div>Drivers: ${data.drivers.join(', ')}</div>
            </div>
          </div>
          
          ${sectionsHTML}
          
          <div class="report-footer">
            Generated by KobayashiAI F1 Analytics - ${new Date().toLocaleString()}
          </div>
        </body>
      </html>
    `
  }

  private generateSectionHTML(section: ReportSection): string {
    switch (section.type) {
      case 'text':
        return `
          <div class="section-title">${section.title}</div>
          <div class="section-content">${section.content}</div>
        `
      
      case 'chart':
        return `
          <div class="section-title">${section.title}</div>
          <div class="chart-placeholder">
            📊 ${section.content || 'Chart visualization'}
            <br><small>Charts are available in the interactive dashboard</small>
          </div>
        `
      
      case 'table':
        if (!section.metadata?.tableData) return ''
        return `
          <div class="section-title">${section.title}</div>
          <table class="report-table">
            ${this.generateTableHTML(section.metadata.tableData)}
          </table>
        `
      
      case 'stats':
        if (!section.metadata?.stats) return ''
        return `
          <div class="section-title">${section.title}</div>
          <div class="stats-grid">
            ${Object.entries(section.metadata.stats).map(([key, value]) => `
              <div class="stat-item">
                <div class="stat-label">${key}:</div>
                <div class="stat-value">${value}</div>
              </div>
            `).join('')}
          </div>
        `
      
      default:
        return ''
    }
  }

  private generateTableHTML(data: any[]): string {
    if (!data || data.length === 0) return ''
    
    const headers = Object.keys(data[0])
    const headerRow = headers.map(header => `<th>${header}</th>`).join('')
    
    const bodyRows = data.map(row => 
      `<tr>${headers.map(header => `<td>${row[header] || '-'}</td>`).join('')}</tr>`
    ).join('')
    
    return `
      <thead>
        <tr>${headerRow}</tr>
      </thead>
      <tbody>
        ${bodyRows}
      </tbody>
    `
  }

  printReport(data: ReportData): void {
    const printWindow = window.open('', '_blank')
    if (!printWindow) {
      throw new Error('Failed to open print window. Please allow popups for this site.')
    }

    printWindow.document.write(this.generatePrintHTML(data))
    printWindow.document.close()
    
    // Wait for content to load, then print
    printWindow.onload = () => {
      setTimeout(() => {
        printWindow.print()
        printWindow.close()
      }, 500)
    }
  }

  downloadAsHTML(data: ReportData): void {
    const htmlContent = this.generatePrintHTML(data)
    const blob = new Blob([htmlContent], { type: 'text/html' })
    const url = URL.createObjectURL(blob)
    
    const link = document.createElement('a')
    link.href = url
    link.download = `${data.title.replace(/\s+/g, '_')}_${data.track.replace(/\s+/g, '_')}_${Date.now()}.html`
    document.body.appendChild(link)
    link.click()
    document.body.removeChild(link)
    URL.revokeObjectURL(url)
  }
}

// Export functions for common report types
export async function exportRaceAnalysisReport(
  track: string,
  tableData: any[],
  stats: Record<string, any>,
  analysisText: string = ''
): Promise<void> {
  const exporter = new F1ReportExporter()
  
  const sections: ReportSection[] = [
    {
      title: 'Executive Summary',
      type: 'text',
      content: analysisText || `This report provides a comprehensive analysis of the race simulation at ${track}. The analysis includes lap time evolution, tire degradation patterns, and performance metrics for strategic decision-making.`
    },
    {
      title: 'Performance Metrics',
      type: 'stats',
      content: 'Key performance indicators and statistics',
      metadata: { stats }
    },
    {
      title: 'Detailed Results',
      type: 'table',
      content: 'Complete race simulation results',
      metadata: { tableData }
    }
  ]
  
  const reportData: ReportData = {
    title: 'F1 Race Analysis Report',
    track,
    date: new Date().toLocaleDateString(),
    drivers: ['Simulation Drivers'],
    sections
  }
  
  try {
    exporter.printReport(reportData)
  } catch (error) {
    console.error('Error exporting report:', error)
    // Fallback to HTML download
    exporter.downloadAsHTML(reportData)
  }
}

export async function exportWhatIfReport(
  track: string,
  scenarios: any[],
  recommendations: string[]
): Promise<void> {
  const exporter = new F1ReportExporter()
  
  const sections: ReportSection[] = [
    {
      title: 'Scenario Analysis',
      type: 'text',
      content: `Analysis of ${scenarios.length} different race scenarios at ${track}. Each scenario was evaluated based on lap time impact, position gain potential, and risk assessment.`
    },
    {
      title: 'Scenario Comparison',
      type: 'table',
      content: 'Comparison of different what-if scenarios',
      metadata: { tableData: scenarios }
    },
    {
      title: 'Strategic Recommendations',
      type: 'text',
      content: recommendations.join('\n\n')
    }
  ]
  
  const reportData: ReportData = {
    title: 'F1 What-If Analysis Report',
    track,
    date: new Date().toLocaleDateString(),
    drivers: ['Analysis Team'],
    sections
  }
  
  try {
    exporter.printReport(reportData)
  } catch (error) {
    console.error('Error exporting report:', error)
    // Fallback to HTML download
    exporter.downloadAsHTML(reportData)
  }
}
